name: Update from Formal Conjectures

on:
  repository_dispatch:
    types: [formal-conjecture-updated] 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python3 scripts/update_formalization_status.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/problems.yaml
          
          if git diff --staged --quiet; then
            echo "🧘 No changes to commit."
          else
            git commit -m "🤖 Auto-update formalization status from formal-conjectures"
            git push
          fi